// Bundles the Life Competencies lesson data into ../assets/lc-data.js (window.LC).
//   cd lc && npm install && node build.mjs
// LC_SRC can point at another checkout of the digital-literacy app.
import * as esbuild from "esbuild";
import os from "node:os";
import path from "node:path";
import fs from "node:fs";

const LC_SRC = process.env.LC_SRC || path.join(os.homedir(), "Codes/digital-literacy/src/lib");
if (!fs.existsSync(LC_SRC)) throw new Error(`Life Competencies source not found at ${LC_SRC}`);

const lcAlias = {
  name: "lc-alias",
  setup(b) {
    b.onResolve({ filter: /^@lc\// }, (a) => b.resolve("./" + a.path.slice(4), { resolveDir: LC_SRC, kind: a.kind }));

    // lessons.ts pulls in Supabase for saving; the Lessons area only needs buildLesson, so stub it out.
    b.onResolve({ filter: /supabase\/client$/ }, () => ({ path: "supabase-stub", namespace: "stub" }));
    b.onLoad({ filter: /.*/, namespace: "stub" }, () => ({ contents: "export const createClient = () => null;", loader: "js" }));
  },
};

await esbuild.build({
  entryPoints: [path.join(import.meta.dirname, "entry.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  globalName: "LC",
  target: "es2020",
  outfile: path.join(import.meta.dirname, "..", "assets", "lc-data.js"),
  plugins: [lcAlias],
  resolveExtensions: [".ts", ".tsx", ".js"],
  define: {
    "process.env.NEXT_PUBLIC_SUPABASE_URL": '""',
    "process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY": '""',
    "process.env.NODE_ENV": '"production"',
  },
  banner: { js: "/* Life Competencies lesson data - generated by lc/build.mjs from the digital-literacy app. */" },
  logLevel: "warning",
});
const out = path.join(import.meta.dirname, "..", "assets", "lc-data.js");
console.log("wrote", out, (fs.statSync(out).size / 1024).toFixed(0) + " KB");
